### ISSUE TITLE
Maybenot 2.2.0 requires 1.88: Could you please make it work with 1.85?

### ISSUE THREAD

**Issue by nmathewson** [maybenot-io/maybenot#34]
Hi!  In arti our MSRV is 1.85.  Our policies mean that we can't upgrade to 1.88 until it has been out for 6 months.

But Maybenot 2.2.0 new requires 1.88, since it uses if-let chains.  When building with 1.85, we get this error:
```
error[E0658]: `let` expressions in this position are unstable
   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/maybenot-2.2.0/src/framework.rs:254:20
    |
254 |                 if let Some(excluded) = excluded
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
error[E0658]: `let` expressions in this position are unstable
   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/maybenot-2.2.0/src/framework.rs:267:20
    |
267 |                 && let Some(excluded) = excluded
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
error[E0658]: `let` expressions in this position are unstable
   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/maybenot-2.2.0/src/framework.rs:581:12
    |
581 |         if let Some(action) = self.machines.as_ref()[mi].states[cs].action
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
```

(from https://gitlab.torproject.org/nickm/arti/-/jobs/1138874)

Could you please put out a maybenot 2.2.1 that builds with Rust 1.85 or earlier?  Thanks!
